### ISSUE TITLE
Bad argument

### ISSUE THREAD

**Issue by ollitapa** [leonhartX/danger-lgtm#10]
I get sporadic errors from danger-lgtm that happens sometimes and goes away after a couple of tries.
``` 
[!] Invalid Dangerfile file: bad argument (expected URI object or URI string)
 #  from Dangerfile:31
 #  -------------------------------------------
 #  # Looks Good To Me
 >  lgtm.check_lgtm
 #  -------------------------------------------
```

My guess would be that the LGTM -service returns a bad url and lgtm crashes? I tried to look at fetch_image_url to check if it would be a good place. 

Maybe use this somewhere?
```
require 'uri'

if url =~ URI::regexp
    # Correct URL
end
```

**Comment by ollitapa** [comment]
More logs

```
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/uri/common.rb:716:in `URI'
  /Users/jenkins/.gem/gems/danger-lgtm-1.0.1/lib/lgtm/plugin.rb:59:in `process_request'
  /Users/jenkins/.gem/gems/danger-lgtm-1.0.1/lib/lgtm/plugin.rb:45:in `fetch_image_url'
  /Users/jenkins/.gem/gems/danger-lgtm-1.0.1/lib/lgtm/plugin.rb:33:in `check_lgtm'
  Dangerfile:31:in `block in parse'
  /Users/jenkins/.gem/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:200:in `eval'
  /Users/jenkins/.gem/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
  /Users/jenkins/.gem/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:196:in `instance_eval'
  /Users/jenkins/.gem/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:196:in `parse'
  /Users/jenkins/.gem/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:274:in `run'
  /Users/jenkins/.gem/gems/danger-5.6.4/lib/danger/danger_core/executor.rb:28:in `run'
  /Users/jenkins/.gem/gems/danger-5.6.4/lib/danger/commands/runner.rb:68:in `run'
  /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/jenkins/.gem/gems/danger-5.6.4/bin/danger:5:in `<top (required)>'
  /Users/jenkins/.gem/bin/danger:22:in `load'
  /Users/jenkins/.gem/bin/danger:22:in `<top (required)>'
```
